import module_for_EX_6
module_for_EX_6.Search_for_a_character_in_the_prescribed_string("RHDjhj9543jutHFDG49jfl", "95")
module_for_EX_6.Return_the_list_of_capital_letters("RHDjhj9543jutHFDG49jfl")
module_for_EX_6.Return_a_list_of_lowercase_letters("RHDjhj9543jutHFDG49jfl")
module_for_EX_6.Return_a_list_of_numeric_characters("RHDjhj9543jutHFDG49jfl")
module_for_EX_6.Checking_the_symbol_for_belonging_to_capital_letters("i")
module_for_EX_6.Checking_the_character_for_belonging_to_lowercase_letters("i")
module_for_EX_6.Checking_the_symbol_for_belonging_to_numbers("i")
module_for_EX_6.Counting_substrings_in_the_specified_string("RHDjhj9543jutHFDG49jfl", "j")